package constants

const (
	ACTION_TYPE_INSERT           = "I"
	ACTION_TYPE_UPDATE           = "U"
	ACTION_TYPE_DELETE           = "D"
	ACTION_TYPE_LIST             = "L"
	ACTION_TYPE_VIEW             = "V"
	ACTION_TYPE_SEARCH           = "S"
	SYSROW_STATUS_PENDING_INSERT = 0
	SYSROW_STATUS_ACTIVE         = 1
	SYSROW_STATUS_PENDING_UPDATE = 2
	SYSROW_STATUS_PENDING_DELETE = 3
	SYSROW_STATUS_RETURN_INSERT  = 4
	SYSROW_STATUS_RETURN_UPDATE  = 5
	APPROVAL_STATUS_PENDING      = 0
	APPROVAL_STATUS_APPROVE      = 1
	APPROVAL_STATUS_REJECT       = 2
	APPROVAL_STATUS_RETURN       = 3
	APPROVAL_STATUS_RETRY        = 4
	APPROVAL_STATUS_DIRECT       = 5
	DATA_STATUS_DELETED          = "Deleted"
	DATA_STATUS_ACTIVE           = "Active"
	DATA_STATUS_PENDING_INSERT   = "Pending Insert"
	DATA_STATUS_PENDING_UPDATE   = "Pending Update"
	DATA_STATUS_PENDING_DELETE   = "Pending Delete"
	DATA_STATUS_PENDING_RETURN   = "Pending Return"
)

var (
	FILTER_PENDING = []int{SYSROW_STATUS_PENDING_INSERT, SYSROW_STATUS_PENDING_DELETE}
)
